text_prompts:
  - In winter, a super real landscape painting of Wuzhen under heavy snow, Jiangnan water town, realistic style,the peony mist is lingering,highly intricate detailed design,by Mark Adamus, lee madgwick,Emmanuel Shiu,Art photography,Trending on artstation:5
  - Chinese myth,mystical, wise, made of rich dream fantasy,delicate, dreamy, ethereal, Backlight,light effect,8k hd wallpaper:3
  - sharp focus, studio shot, intricate detail, highly detailed:3
  - jpeg artifacts, blur, clouds, people:-1

init_image:
width_height: [ 640, 1024 ]

skip_steps: 0
steps: 250

init_scale: 1000
clip_guidance_scale: 50000

tv_scale: 100000
range_scale: 150000
sat_scale: 205000
cutn_batches: 4

diffusion_model: 512x512_diffusion_uncond_finetune_008100
use_secondary_model: False
diffusion_sampling_mode: ddim

perlin_init: False
perlin_mode: mixed
seed:
eta: 0.65
clamp_grad: True
clamp_max: 0.25

randomize_class: True
clip_denoised: False
rand_mag: 0.05

cut_overview: "[12]*400+[4]*600"
cut_innercut: "[2]*200+[4]*300+[12]*400+[16]*100"
cut_icgray_p: "[0.2]*400+[0]*600"
cut_ic_pow: 10.

save_rate: 20
gif_fps: 20
gif_size_ratio: 0.5
n_batches: 1
batch_size: 2
batch_name:
clip_models:
  - ViT-B-32::openai
  - ViT-B-16::openai
  - RN50::openai
clip_models_schedules:

use_vertical_symmetry: False
use_horizontal_symmetry: False
transformation_percent: [0.09]

on_misspelled_token: ignore
diffusion_model_config:
cut_schedules_group:
name_docarray:
skip_event:
stop_event:
text_clip_on_cpu: False
truncate_overlength_prompt: False
image_output: True
visualize_cuts: False
display_rate: 1
